In [135]:
import numpy as np
import pandas as pd

# Series

In [136]:
my_index = ['Baku', 'Absheron', 'Sumqayit', 'Ganja']

In [137]:
my_data = [10, 1, 50, 20]

In [138]:
my_series = pd.Series(data=my_data, index=my_index)

In [139]:
my_series

Baku        10
Absheron     1
Sumqayit    50
Ganja       20
dtype: int64

In [140]:
my_series['Ganja']

np.int64(20)

In [141]:
ages = {'Nadir': 46, 'Ali':25, 'Ivan':32, 'Kolivan': 57}

In [142]:
pd.Series(ages)

Nadir      46
Ali        25
Ivan       32
Kolivan    57
dtype: int64

In [143]:
q1 = {'Baku': 53200, 'Absheron':23500, 'Sumqayit': 152000, 'Ganja': 2300}
q2 = { 'Brazil': 256000, 'Sumqayit': 5684,'Baku': 48200, 'Spain': 56874}

In [144]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [145]:
sales_q1

Baku         53200
Absheron     23500
Sumqayit    152000
Ganja         2300
dtype: int64

In [146]:
sales_q2

Brazil      256000
Sumqayit      5684
Baku         48200
Spain        56874
dtype: int64

In [147]:
sales_q1.keys(), sales_q2.keys()

(Index(['Baku', 'Absheron', 'Sumqayit', 'Ganja'], dtype='str'),
 Index(['Brazil', 'Sumqayit', 'Baku', 'Spain'], dtype='str'))

In [148]:
sales_q1 * 2

Baku        106400
Absheron     47000
Sumqayit    304000
Ganja         4600
dtype: int64

In [149]:
sales_q1 + sales_q2

Absheron         NaN
Baku        101400.0
Brazil           NaN
Ganja            NaN
Spain            NaN
Sumqayit    157684.0
dtype: float64

In [150]:
first_half = sales_q1.add(sales_q2, fill_value=0)
first_half

Absheron     23500.0
Baku        101400.0
Brazil      256000.0
Ganja         2300.0
Spain        56874.0
Sumqayit    157684.0
dtype: float64

# DataFrame

In [151]:
my_columns = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']

In [152]:
np.random.seed(42)
my_data = np.random.randint(15, 30, (4, 5))

In [153]:
df = pd.DataFrame(my_data, columns=my_columns, index=my_index)

In [154]:
df

          Monday  Tuesday  Wednesday  Thursday  Friday
Baku          21       18         27        29      25
Absheron      22       27         19        21      24
Sumqayit      17       21         25        25      22
Ganja         19       18         22        22      17

In [155]:
df.info()

<class 'pandas.DataFrame'>
Index: 4 entries, Baku to Ganja
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Monday     4 non-null      int32
 1   Tuesday    4 non-null      int32
 2   Wednesday  4 non-null      int32
 3   Thursday   4 non-null      int32
 4   Friday     4 non-null      int32
dtypes: int32(5)
memory usage: 112.0+ bytes

In [156]:
employees_df = pd.read_csv('data/employees.csv')
employees_df

,ID,Name,Age,Country,Salary,ExperienceYears,Remote,Department
0,1,Lucy,56.0,USA,30854.0,15.0,Yes,IT
1,2,Victoria,46.0,Azerbaijan,68623.0,11.0,Yes,HR
2,3,Benjamin,32.0,Germany,37392.0,18.0,No,Marketing
3,4,Luna,25.0,USA,85680.0,13.0,No,Finance
4,5,Zoe,38.0,Brazil,76717.0,5.0,Yes,Design
...,...,...,...,...,...,...,...,...
95,96,Abigail,59.0,USA,52399.0,16.0,Yes,Finance
96,97,Harper,56.0,NaN,76214.0,18.0,Yes,IT
97,98,Owen,58.0,France,116416.0,4.0,No,Design
98,99,Ethan,45.0,USA,100271.0,8.0,Yes,Design
99,100,Grayson,24.0,Germany,74064.0,11.0,Yes,HR

In [157]:
employees_df.columns

Index(['ID', 'Name', 'Age', 'Country', 'Salary', 'ExperienceYears', 'Remote',
       'Department'],
      dtype='str')

In [158]:
employees_df.head()

   ID      Name   Age     Country   Salary  ExperienceYears Remote Department
0   1      Lucy  56.0         USA  30854.0             15.0    Yes         IT
1   2  Victoria  46.0  Azerbaijan  68623.0             11.0    Yes         HR
2   3  Benjamin  32.0     Germany  37392.0             18.0     No  Marketing
3   4      Luna  25.0         USA  85680.0             13.0     No    Finance
4   5       Zoe  38.0      Brazil  76717.0              5.0    Yes     Design

In [159]:
employees_df.head(8)

,ID,Name,Age,Country,Salary,ExperienceYears,Remote,Department
0,1,Lucy,56.0,USA,30854.0,15.0,Yes,IT
1,2,Victoria,46.0,Azerbaijan,68623.0,11.0,Yes,HR
2,3,Benjamin,32.0,Germany,37392.0,18.0,No,Marketing
3,4,Luna,25.0,USA,85680.0,13.0,No,Finance
4,5,Zoe,38.0,Brazil,76717.0,5.0,Yes,Design
5,6,Sebastian,56.0,Japan,117092.0,5.0,Yes,Design
6,7,Paisley,36.0,France,80859.0,12.0,No,NaN
7,8,Jaxon,NaN,Azerbaijan,56309.0,18.0,No,HR

In [160]:
employees_df.tail()

     ID     Name   Age  Country    Salary  ExperienceYears Remote Department
95   96  Abigail  59.0      USA   52399.0             16.0    Yes    Finance
96   97   Harper  56.0      NaN   76214.0             18.0    Yes         IT
97   98     Owen  58.0   France  116416.0              4.0     No     Design
98   99    Ethan  45.0      USA  100271.0              8.0    Yes     Design
99  100  Grayson  24.0  Germany   74064.0             11.0    Yes         HR

In [161]:
employees_df.tail(8)

     ID      Name   Age  Country    Salary  ExperienceYears Remote Department
92   93    Samuel  52.0   France  116831.0             17.0    Yes         IT
93   94      Nora  50.0      USA   33987.0              9.0    Yes         HR
94   95  Penelope  22.0    Japan   88871.0             18.0    Yes         HR
95   96   Abigail  59.0      USA   52399.0             16.0    Yes    Finance
96   97    Harper  56.0      NaN   76214.0             18.0    Yes         IT
97   98      Owen  58.0   France  116416.0              4.0     No     Design
98   99     Ethan  45.0      USA  100271.0              8.0    Yes     Design
99  100   Grayson  24.0  Germany   74064.0             11.0    Yes         HR

In [162]:
employees_df.sample(5)

    ID    Name   Age     Country    Salary  ExperienceYears Remote Department
44  45   David  37.0       Japan   38155.0              7.0     No    Finance
4    5     Zoe  38.0      Brazil   76717.0              5.0    Yes     Design
53  54  Amelia  21.0  Azerbaijan   76843.0             12.0     No         IT
42  43  Nathan  43.0     Germany   67504.0              1.0     No         IT
10  11   Logan  41.0      France  100467.0              0.0     No         HR

In [163]:
employees_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               100 non-null    int64
 1   Name             100 non-null    str
 2   Age              97 non-null     float64
 3   Country          99 non-null     str
 4   Salary           96 non-null     float64
 5   ExperienceYears  99 non-null     float64
 6   Remote           99 non-null     str
 7   Department       99 non-null     str
dtypes: float64(3), int64(1), str(4)
memory usage: 6.4 KB

In [164]:
employees_df.describe()

               ID        Age         Salary  ExperienceYears
count  100.000000  97.000000      96.000000        99.000000
mean    50.500000  38.103093   73169.104167         9.505051
std     29.011492  12.266557   27190.585615         6.081712
min      1.000000  18.000000   30854.000000         0.000000
25%     25.750000  27.000000   49860.500000         4.000000
50%     50.500000  38.000000   75139.000000        10.000000
75%     75.250000  47.000000   95972.250000        15.000000
max    100.000000  59.000000  119045.000000        19.000000

In [165]:
employees_df["Age"].mean()

np.float64(38.103092783505154)

In [166]:
employees_df['Age'].max()

np.float64(59.0)

In [167]:
employees_df[employees_df['Age'] > 35]

,ID,Name,Age,Country,Salary,ExperienceYears,Remote,Department
0,1,Lucy,56.0,USA,30854.0,15.0,Yes,IT
1,2,Victoria,46.0,Azerbaijan,68623.0,11.0,Yes,HR
4,5,Zoe,38.0,Brazil,76717.0,5.0,Yes,Design
5,6,Sebastian,56.0,Japan,117092.0,5.0,Yes,Design
6,7,Paisley,36.0,France,80859.0,12.0,No,NaN
10,11,Logan,41.0,France,100467.0,0.0,No,HR
11,12,Riley,53.0,USA,82662.0,14.0,Yes,Marketing
12,13,Elijah,57.0,France,42688.0,0.0,No,IT
13,14,Emma,41.0,Japan,55342.0,4.0,Yes,HR
15,16,Grace,39.0,France,97863.0,18.0,Yes,HR
17,18,Ellie,41.0,Japan,95733.0,2.0,Yes,HR
18,19,Oliver,47.0,Germany,119045.0,16.0,Yes,HR
19,20,Evelyn,55.0,Brazil,64698.0,16.0,No,Marketing
21,22,Hunter,38.0,USA,52671.0,13.0,Yes,Finance
22,23,Christopher,50.0,Germany,55184.0,5.0,No,HR
24,25,Isaac,39.0,Azerbaijan,116202.0,8.0,Yes,HR
25,26,Anthony,42.0,Japan,81663.0,4.0,Yes,Design
26,27,Audrey,44.0,France,45708.0,16.0,No,Marketing
27,28,Thomas,59.0,USA,79811.0,13.0,No,Design
28,29,Ella,45.0,Azerbaijan,32811.0,2.0,No,Finance
32,33,Eleanor,54.0,Japan,41411.0,2.0,Yes,IT
34,35,Emilia,38.0,France,97270.0,9.0,No,HR
36,37,Leah,56.0,Azerbaijan,38680.0,7.0,Yes,IT
39,40,Alexander,42.0,France,101295.0,14.0,No,Marketing
42,43,Nathan,43.0,Germany,67504.0,1.0,No,IT
44,45,David,37.0,Japan,38155.0,7.0,No,Finance
45,46,Zo?,45.0,Brazil,103656.0,0.0,No,IT
48,49,Noah,52.0,Brazil,51918.0,15.0,No,Marketing
51,52,Ezra,53.0,Azerbaijan,60306.0,2.0,No,IT
52,53,Dylan,57.0,Azerbaijan,46646.0,17.0,Yes,Finance
56,57,Lillian,59.0,France,32049.0,12.0,Yes,Marketing
58,59,Zoey,46.0,Azerbaijan,50932.0,0.0,No,Finance
60,61,Hudson,43.0,Brazil,91434.0,13.0,Yes,Design
61,62,Isabella,51.0,USA,102694.0,NaN,No,IT
63,64,James,53.0,USA,37400.0,11.0,No,Finance
65,66,Adrian,48.0,Brazil,45151.0,14.0,No,Finance
69,70,Jackson,40.0,USA,36295.0,16.0,No,Design
70,71,Lily,57.0,France,89040.0,19.0,Yes,Design
71,72,Joshua,38.0,Brazil,42183.0,9.0,No,Marketing
74,75,Aurora,41.0,Brazil,62711.0,10.0,No,Finance
75,76,Everly,43.0,Japan,35539.0,4.0,No,Marketing
76,77,Christian,42.0,USA,83351.0,0.0,No,Design
77,78,Ryan,58.0,France,91267.0,7.0,No,Finance
78,79,Michael,46.0,Germany,78354.0,11.0,Yes,Design
81,82,Sophia,42.0,Brazil,112018.0,6.0,No,Design
84,85,William,41.0,USA,76975.0,12.0,Yes,HR
87,88,Stella,41.0,Germany,32869.0,2.0,No,Design
91,92,John,52.0,Germany,53328.0,12.0,Yes,Finance
92,93,Samuel,52.0,France,116831.0,17.0,Yes,IT
93,94,Nora,50.0,USA,33987.0,9.0,Yes,HR
95,96,Abigail,59.0,USA,52399.0,16.0,Yes,Finance
96,97,Harper,56.0,NaN,76214.0,18.0,Yes,IT
97,98,Owen,58.0,France,116416.0,4.0,No,Design
98,99,Ethan,45.0,USA,100271.0,8.0,Yes,Design

In [168]:
employees_df['Age'].value_counts()

Age
41.0    6
25.0    5
56.0    4
32.0    4
38.0    4
19.0    4
42.0    4
24.0    4
31.0    4
46.0    3
28.0    3
53.0    3
57.0    3
59.0    3
45.0    3
26.0    3
21.0    3
43.0    3
52.0    3
39.0    2
50.0    2
33.0    2
34.0    2
35.0    2
58.0    2
18.0    2
36.0    1
47.0    1
55.0    1
29.0    1
44.0    1
20.0    1
54.0    1
37.0    1
23.0    1
51.0    1
27.0    1
48.0    1
40.0    1
22.0    1
Name: count, dtype: int64

In [169]:
employees_df['Country'].value_counts()

Country
USA           21
Azerbaijan    18
France        18
Brazil        17
Japan         14
Germany       11
Name: count, dtype: int64

In [170]:
employees_df.groupby('Country')['Salary'].mean()

Country
Azerbaijan    72012.555556
Brazil        76554.687500
France        83509.823529
Germany       62115.000000
Japan         75420.615385
USA           67175.950000
Name: Salary, dtype: float64

SELECT Country, AVG(Salary)

FROM Employees

GROU BY Country

In [171]:
employees_df.index

RangeIndex(start=0, stop=100, step=1)

In [172]:
employees_df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ID,100.0,50.500000,29.011492,1.0,25.75,50.5,75.25,100.0
Age,97.0,38.103093,12.266557,18.0,27.00,38.0,47.00,59.0
Salary,96.0,73169.104167,27190.585615,30854.0,49860.50,75139.0,95972.25,119045.0
ExperienceYears,99.0,9.505051,6.081712,0.0,4.00,10.0,15.00,19.0

In [173]:
employees_df['Country']

0            USA
1     Azerbaijan
2        Germany
3            USA
4         Brazil
         ...
95           USA
96           NaN
97        France
98           USA
99       Germany
Name: Country, Length: 100, dtype: str

In [174]:
employees_df[['Country', 'Name']]

       Country      Name
0          USA      Lucy
1   Azerbaijan  Victoria
2      Germany  Benjamin
3          USA      Luna
4       Brazil       Zoe
..         ...       ...
95         USA   Abigail
96         NaN    Harper
97      France      Owen
98         USA     Ethan
99     Germany   Grayson

[100 rows x 2 columns]

In [175]:
employees_df.drop('Country', axis=1, inplace=True)

C:\Users\mr13\AppData\Local\Temp\ipykernel_16620\1195665830.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  employees_df.drop('Country', axis=1, inplace=True)

In [176]:
employees_df

     ID      Name   Age    Salary  ExperienceYears Remote Department
0     1      Lucy  56.0   30854.0             15.0    Yes         IT
1     2  Victoria  46.0   68623.0             11.0    Yes         HR
2     3  Benjamin  32.0   37392.0             18.0     No  Marketing
3     4      Luna  25.0   85680.0             13.0     No    Finance
4     5       Zoe  38.0   76717.0              5.0    Yes     Design
..  ...       ...   ...       ...              ...    ...        ...
95   96   Abigail  59.0   52399.0             16.0    Yes    Finance
96   97    Harper  56.0   76214.0             18.0    Yes         IT
97   98      Owen  58.0  116416.0              4.0     No     Design
98   99     Ethan  45.0  100271.0              8.0    Yes     Design
99  100   Grayson  24.0   74064.0             11.0    Yes         HR

[100 rows x 7 columns]

In [177]:
employees_df.drop(0, axis=0, inplace=True)
employees_df

C:\Users\mr13\AppData\Local\Temp\ipykernel_16620\2096718232.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  employees_df.drop(0, axis=0, inplace=True)

     ID       Name   Age    Salary  ExperienceYears Remote Department
1     2   Victoria  46.0   68623.0             11.0    Yes         HR
2     3   Benjamin  32.0   37392.0             18.0     No  Marketing
3     4       Luna  25.0   85680.0             13.0     No    Finance
4     5        Zoe  38.0   76717.0              5.0    Yes     Design
5     6  Sebastian  56.0  117092.0              5.0    Yes     Design
..  ...        ...   ...       ...              ...    ...        ...
95   96    Abigail  59.0   52399.0             16.0    Yes    Finance
96   97     Harper  56.0   76214.0             18.0    Yes         IT
97   98       Owen  58.0  116416.0              4.0     No     Design
98   99      Ethan  45.0  100271.0              8.0    Yes     Design
99  100    Grayson  24.0   74064.0             11.0    Yes         HR

[99 rows x 7 columns]

In [178]:
employees_df.shape

(99, 7)

In [179]:
employees_df.set_index("Name", inplace=True)

C:\Users\mr13\AppData\Local\Temp\ipykernel_16620\1379931669.py:1: Pandas4Warning: The inplace keyword in DataFrame.set_index is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  employees_df.set_index("Name", inplace=True)

In [180]:
employees_df

            ID   Age    Salary  ExperienceYears Remote Department
Name
Victoria     2  46.0   68623.0             11.0    Yes         HR
Benjamin     3  32.0   37392.0             18.0     No  Marketing
Luna         4  25.0   85680.0             13.0     No    Finance
Zoe          5  38.0   76717.0              5.0    Yes     Design
Sebastian    6  56.0  117092.0              5.0    Yes     Design
...        ...   ...       ...              ...    ...        ...
Abigail     96  59.0   52399.0             16.0    Yes    Finance
Harper      97  56.0   76214.0             18.0    Yes         IT
Owen        98  58.0  116416.0              4.0     No     Design
Ethan       99  45.0  100271.0              8.0    Yes     Design
Grayson    100  24.0   74064.0             11.0    Yes         HR

[99 rows x 6 columns]

In [181]:
employees_df.loc['Sebastian']

ID                        6
Age                    56.0
Salary             117092.0
ExperienceYears         5.0
Remote                  Yes
Department           Design
Name: Sebastian, dtype: object

In [182]:
employees_df.iloc[3]

ID                       5
Age                   38.0
Salary             76717.0
ExperienceYears        5.0
Remote                 Yes
Department          Design
Name: Zoe, dtype: object

In [183]:
employees_df.dtypes

ID                   int64
Age                float64
Salary             float64
ExperienceYears    float64
Remote                 str
Department             str
dtype: object

In [184]:
employees_df['Department'].str.lower()

Name
Victoria            hr
Benjamin     marketing
Luna           finance
Zoe             design
Sebastian       design
               ...
Abigail        finance
Harper              it
Owen            design
Ethan           design
Grayson             hr
Name: Department, Length: 99, dtype: str

In [185]:
employees_df['Department'].str.contains('Design')

Name
Victoria     False
Benjamin     False
Luna         False
Zoe           True
Sebastian     True
             ...
Abigail      False
Harper       False
Owen          True
Ethan         True
Grayson      False
Name: Department, Length: 99, dtype: bool

In [186]:
employees_df['Age'] += 1
employees_df['Age']

Name
Victoria     47.0
Benjamin     33.0
Luna         26.0
Zoe          39.0
Sebastian    57.0
             ...
Abigail      60.0
Harper       57.0
Owen         59.0
Ethan        46.0
Grayson      25.0
Name: Age, Length: 99, dtype: float64

In [187]:
employees_df.rename(columns={'Salary':'Зарплата'}, inplace=True)
employees_df

C:\Users\mr13\AppData\Local\Temp\ipykernel_16620\188765807.py:1: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  employees_df.rename(columns={'Salary':'Зарплата'}, inplace=True)

            ID   Age  Зарплата  ExperienceYears Remote Department
Name
Victoria     2  47.0   68623.0             11.0    Yes         HR
Benjamin     3  33.0   37392.0             18.0     No  Marketing
Luna         4  26.0   85680.0             13.0     No    Finance
Zoe          5  39.0   76717.0              5.0    Yes     Design
Sebastian    6  57.0  117092.0              5.0    Yes     Design
...        ...   ...       ...              ...    ...        ...
Abigail     96  60.0   52399.0             16.0    Yes    Finance
Harper      97  57.0   76214.0             18.0    Yes         IT
Owen        98  59.0  116416.0              4.0     No     Design
Ethan       99  46.0  100271.0              8.0    Yes     Design
Grayson    100  25.0   74064.0             11.0    Yes         HR

[99 rows x 6 columns]

In [188]:
employees_df.sort_values(by='Age')

          ID   Age  Зарплата  ExperienceYears Remote Department
Name
Leo       86  19.0   51357.0             19.0     No     Design
Ava       81  19.0   68360.0              4.0    Yes     Design
Scarlett  17  20.0   82083.0              3.0     No         HR
Olivia    21  20.0       NaN             11.0    Yes         IT
Julian    55  20.0   46371.0              6.0     No     Design
...       ..   ...       ...              ...    ...        ...
Lillian   57  60.0   32049.0             12.0    Yes  Marketing
Abigail   96  60.0   52399.0             16.0    Yes    Finance
Jaxon      8   NaN   56309.0             18.0     No         HR
Jacob     15   NaN       NaN             15.0    Yes     Design
Aria      38   NaN  114896.0             13.0    Yes  Marketing

[99 rows x 6 columns]

In [189]:
employees_df.sort_values(by='Age', ascending=False)

         ID   Age  Зарплата  ExperienceYears Remote Department
Name
Thomas   28  60.0   79811.0             13.0     No     Design
Lillian  57  60.0   32049.0             12.0    Yes  Marketing
Abigail  96  60.0   52399.0             16.0    Yes    Finance
Ryan     78  59.0   91267.0              7.0     No    Finance
Owen     98  59.0  116416.0              4.0     No     Design
...      ..   ...       ...              ...    ...        ...
Ava      81  19.0   68360.0              4.0    Yes     Design
Leo      86  19.0   51357.0             19.0     No     Design
Jaxon     8   NaN   56309.0             18.0     No         HR
Jacob    15   NaN       NaN             15.0    Yes     Design
Aria     38   NaN  114896.0             13.0    Yes  Marketing

[99 rows x 6 columns]

In [190]:
employees_df.isna().sum()

ID                 0
Age                3
Зарплата           4
ExperienceYears    1
Remote             1
Department         1
dtype: int64

In [191]:
employees_df.dropna()

            ID   Age  Зарплата  ExperienceYears Remote Department
Name
Victoria     2  47.0   68623.0             11.0    Yes         HR
Benjamin     3  33.0   37392.0             18.0     No  Marketing
Luna         4  26.0   85680.0             13.0     No    Finance
Zoe          5  39.0   76717.0              5.0    Yes     Design
Sebastian    6  57.0  117092.0              5.0    Yes     Design
...        ...   ...       ...              ...    ...        ...
Abigail     96  60.0   52399.0             16.0    Yes    Finance
Harper      97  57.0   76214.0             18.0    Yes         IT
Owen        98  59.0  116416.0              4.0     No     Design
Ethan       99  46.0  100271.0              8.0    Yes     Design
Grayson    100  25.0   74064.0             11.0    Yes         HR

[90 rows x 6 columns]

In [193]:
employees_df['Зарплата'].fillna(employees_df['Зарплата'].mean())

Name
Victoria      68623.0
Benjamin      37392.0
Luna          85680.0
Zoe           76717.0
Sebastian    117092.0
               ...
Abigail       52399.0
Harper        76214.0
Owen         116416.0
Ethan        100271.0
Grayson       74064.0
Name: Зарплата, Length: 99, dtype: float64

In [195]:
employees_df['Department'].unique()

<StringArray>
['HR', 'Marketing', 'Finance', 'Design', nan, 'IT']
Length: 6, dtype: str

In [196]:
employees_df['Department'].nunique()

5

In [197]:
employees_df.set_index('ID', inplace=True)

C:\Users\mr13\AppData\Local\Temp\ipykernel_16620\2312103588.py:1: Pandas4Warning: The inplace keyword in DataFrame.set_index is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  employees_df.set_index('ID', inplace=True)

In [198]:
employees_df

      Age  Зарплата  ExperienceYears Remote Department
ID
2    47.0   68623.0             11.0    Yes         HR
3    33.0   37392.0             18.0     No  Marketing
4    26.0   85680.0             13.0     No    Finance
5    39.0   76717.0              5.0    Yes     Design
6    57.0  117092.0              5.0    Yes     Design
..    ...       ...              ...    ...        ...
96   60.0   52399.0             16.0    Yes    Finance
97   57.0   76214.0             18.0    Yes         IT
98   59.0  116416.0              4.0     No     Design
99   46.0  100271.0              8.0    Yes     Design
100  25.0   74064.0             11.0    Yes         HR

[99 rows x 5 columns]

In [199]:
employees_df.reset_index(inplace=True)
employees_df

C:\Users\mr13\AppData\Local\Temp\ipykernel_16620\1039864176.py:1: Pandas4Warning: The inplace keyword in DataFrame.reset_index is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  employees_df.reset_index(inplace=True)

     ID   Age  Зарплата  ExperienceYears Remote Department
0     2  47.0   68623.0             11.0    Yes         HR
1     3  33.0   37392.0             18.0     No  Marketing
2     4  26.0   85680.0             13.0     No    Finance
3     5  39.0   76717.0              5.0    Yes     Design
4     6  57.0  117092.0              5.0    Yes     Design
..  ...   ...       ...              ...    ...        ...
94   96  60.0   52399.0             16.0    Yes    Finance
95   97  57.0   76214.0             18.0    Yes         IT
96   98  59.0  116416.0              4.0     No     Design
97   99  46.0  100271.0              8.0    Yes     Design
98  100  25.0   74064.0             11.0    Yes         HR

[99 rows x 6 columns]